from datetime import datetime

from dashboard.database import db


class AssessmentRecord(db.Model):

    __tablename__ = "assessment_records"

    assessment_id = db.Column(
        db.Integer,
        primary_key=True
    )

    # ======================================================
    # Patient Information
    # ======================================================

    patient_id = db.Column(
        db.Integer,
        db.ForeignKey("patients.patient_id"),
        nullable=False
    )

    # ======================================================
    # Assessment Information
    # ======================================================

    exercise = db.Column(
        db.String(100),
        nullable=False
    )

    repetitions = db.Column(
        db.Integer,
        nullable=False
    )

    average_score = db.Column(
        db.Float,
        nullable=False
    )

    best_score = db.Column(
        db.Float,
        nullable=False
    )

    worst_score = db.Column(
        db.Float,
        nullable=False
    )

    trend = db.Column(
        db.String(50)
    )

    # Full clinical feedback generated by NeuroMotion.
    # Stored as a JSON string so every assessment remains
    # a permanent snapshot of the original report.
    feedback = db.Column(
        db.Text
    )

    # Therapist notes entered after reviewing the assessment.
    notes = db.Column(
        db.Text
    )

    created_at = db.Column(
        db.DateTime,
        default=datetime.utcnow
    )

    def __repr__(self):
        return (
            f"<AssessmentRecord "
            f"{self.assessment_id} "
            f"Patient={self.patient_id}>"
        )