"""Initial database schema

Revision ID: cf5a5f57fb40
Revises: 
Create Date: 2026-07-28 15:34:20.541237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf5a5f57fb40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repetitions', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('average_score', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('best_score', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('worst_score', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('trend', sa.String(length=50), nullable=True))
        batch_op.drop_column('score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.FLOAT(), nullable=True))
        batch_op.drop_column('trend')
        batch_op.drop_column('worst_score')
        batch_op.drop_column('best_score')
        batch_op.drop_column('average_score')
        batch_op.drop_column('repetitions')

    # ### end Alembic commands ###
